# .github/workflows/data_diff_ci.yml

name: 'CI - Data Diff'

# Define o gatilho: rodar sempre que um PR for aberto ou atualizado
on:
  pull_request:
    branches:
      - main # Ou a sua branch principal

      # ADICIONE ESTE BLOCO AQUI
permissions:
  pull-requests: write # Permissão para escrever comentários no PR
jobs:
  run-data-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Rodar Joyce Data Diff Action
        # Troque 'joycejdiong' pelo seu usuário
        uses: joycejdm/data-diff-action@main 
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # --- NOVAS LINHAS ---
          sf_account: ${{ secrets.SF_ACCOUNT }}
          sf_region: ${{ secrets.SF_REGION }}
          sf_user: ${{ secrets.SF_USER }}
          sf_password: ${{ secrets.SF_PASSWORD }}
          sf_role: ${{ secrets.SF_ROLE }}
          sf_warehouse: ${{ secrets.SF_WAREHOUSE }}
          sf_database: ${{ secrets.SF_DATABASE }}
          sf_schema: ${{ secrets.SF_SCHEMA }}