# .github/workflows/generate_manifest.yml

name: 'Produção - Gerar Manifest'

on:
  push:
    branches:
      - main # Roda sempre que houver um push/merge na main

jobs:
  build-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dbt-snowflake
        run: pip install dbt-snowflake

      - name: Criar o profiles.yml
        # Este comando 'echo' cria o profiles.yml que o dbt precisa
        run: |
          mkdir -p ~/.dbt
          echo "default:" > ~/.dbt/profiles.yml
          echo "  target: prod" >> ~/.dbt/profiles.yml
          echo "  outputs:" >> ~/.dbt/profiles.yml
          echo "    prod:" >> ~/.dbt/profiles.yml
          echo "      type: snowflake" >> ~/.dbt/profiles.yml
          echo "      account: ${{ secrets.SF_ACCOUNT }}" >> ~/.dbt/profiles.yml
          echo "      user: ${{ secrets.SF_USER }}" >> ~/.dbt/profiles.yml
          echo "      password: ${{ secrets.SF_PASSWORD }}" >> ~/.dbt/profiles.yml
          echo "      role: ${{ secrets.SF_ROLE }}" >> ~/.dbt/profiles.yml
          echo "      warehouse: ${{ secrets.SF_WAREHOUSE }}" >> ~/.dbt/profiles.yml
          echo "      database: ${{ secrets.SF_DATABASE }}" >> ~/.dbt/profiles.yml
          echo "      schema: ${{ secrets.SF_SCHEMA }}" >> ~/.dbt/profiles.yml
          echo "      threads: 1" >> ~/.dbt/profiles.yml

      - name: Corrigir o profile: do dbt_project.yml
        # Este é o mesmo "fix" que fizemos no PR de teste,
        # para garantir que o dbt usa o perfil 'default'
        run: |
          sed -i "s/profile: 'dbt_cobaia_project'/profile: 'default'/g" dbt_cobaia_project/dbt_project.yml
          sed -i "s/profile: 'default'/profile: 'default'/g" dbt_cobaia_project/dbt_project.yml # Garante que funciona

      - name: Rodar dbt deps
        run: dbt deps
        working-directory: ./dbt_cobaia_project

      - name: Rodar dbt parse (para gerar o manifest)
        run: dbt parse
        working-directory: ./dbt_cobaia_project

      - name: Guardar o manifest.json como Artefacto
        uses: actions/upload-artifact@v4
        with:
          name: prod-manifest # O nome do nosso artefacto
          path: ./dbt_cobaia_project/target/manifest.json # O ficheiro a guardar
          retention-days: 5 # Guarda só por 5 dias